CREATE TABLE IF NOT EXISTS client (
    username VARCHAR(255) NOT NULL,
    chat_id BIGINT PRIMARY KEY NOT NULL,
    status BOOLEAN DEFAULT FALSE NOT NULL,
    is_tested BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_client_status ON client(status);
